FROM mcr.microsoft.com/devcontainers/typescript-node:0-18

RUN apt-get update && apt-get upgrade -y
# Electron dependencies
RUN apt-get install -y libnss3 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgtk-3-0 libgbm1 libasound2

USER node
# jj version control
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN sudo apt-get install -y libssl-dev openssl pkg-config build-essential
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
RUN $HOME/.cargo/bin/cargo-binstall --strategies crate-meta-data jj-cli